title: <p align="center"> Thahura Naaz Shaik </p>
logo:  <p align="center">/assets/img/Thahura.png</p>
         
description:
  <p align="center">
  <a href="https://www.linkedin.com/in/thahura-naaz-69a18a4/">LinkedIn</a> |
  <a href="https://github.com/thahura111">GitHub</a>  
   
  <br> 
  
  I'm currently learning ML and AI and looking forward to apply them in telecom/networking domain
   <br>
  </p>



theme: jekyll-theme-minimal
