title: <p align="center"> Thahura Naaz Shaik </p>
logo: <p align="center">
     <img src="assets/img/Thahura.png" 
     width="600" 
     height="700" />
     </p>
description:
  <p align="center">
  <a href="https://www.linkedin.com/in/thahura-naaz-69a18a4/">LinkedIn</a> |
  <a href="https://github.com/thahura111">GitHub</a>  
   </p>
  <br> 
   <p align="left">
  I'm currently learning ML and AI and looking forward to apply them in telecom/networking domain
   
 
  
  
  
  
  
  
  
  
theme: jekyll-theme-minimal
